# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-23 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('Admin_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Admin_Username', models.CharField(max_length=128)),
                ('Admin_Password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('Customer_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=128)),
                ('Customer_Category', models.CharField(max_length=128)),
                ('PhoneNum', models.IntegerField()),
                ('Customer_Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('Equip_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Equip_Name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenances',
            fields=[
                ('Mainten_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Mainten_Date', models.DateField()),
                ('Deprecation', models.CharField(max_length=250)),
                ('Equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Equipments')),
            ],
        ),
        migrations.CreateModel(
            name='Material_Inventory',
            fields=[
                ('Material_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Material_Name', models.CharField(max_length=128)),
                ('Material_Category', models.CharField(max_length=128)),
                ('Material_Surplus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateField()),
                ('Product_Case', models.IntegerField()),
                ('Description', models.CharField(max_length=250)),
                ('Delivery_Date', models.DateField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('Purchase_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Purchase_Date', models.DateField()),
                ('Purchase_Quantity', models.IntegerField()),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Material_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Inventory',
            fields=[
                ('Product_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Pro_Category', models.CharField(max_length=128)),
                ('Surplus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Production_Activity',
            fields=[
                ('Activity_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Act_Date', models.DateField()),
                ('Act_Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('WorkNum', models.AutoField(primary_key=True, serialize=False)),
                ('Staff_Name', models.CharField(max_length=128)),
                ('Department', models.CharField(max_length=128)),
                ('Staff_Gender', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('Supplier_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(max_length=128)),
                ('Liaison_Name', models.CharField(max_length=128)),
                ('Liaison_Number', models.IntegerField()),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Material_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('Warehouse_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Storage_Type', models.CharField(max_length=128)),
                ('Warehouse_Location', models.CharField(max_length=128)),
                ('PeopleInCharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='production_activity',
            name='ActResponStaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Staff'),
        ),
        migrations.AddField(
            model_name='production_activity',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Product_Inventory'),
        ),
        migrations.AddField(
            model_name='production_activity',
            name='Warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Warehouse'),
        ),
        migrations.AddField(
            model_name='product_inventory',
            name='Warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Warehouse'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='ResponsibleStaff',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='Beer.Staff'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='Supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Suppliers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Product_Inventory'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ResponsibleMan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Staff'),
        ),
        migrations.AddField(
            model_name='material_inventory',
            name='Warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Warehouse'),
        ),
        migrations.AddField(
            model_name='maintenances',
            name='MaintenStaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Staff'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='Warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Warehouse'),
        ),
        migrations.AddField(
            model_name='administrators',
            name='WorkNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beer.Staff'),
        ),
    ]
